server:
  port: 7300
soma: 
  url: 'http://10.8.38.232:8087/sum/'
sub:
  url: 'http://10.8.38.232:8088/sub/'
raiz:
  url: 'http://10.8.38.232:9000/squareroot/'
div:
  url: 'http://10.8.38.232:8020/divisao/'
mult:
  url: 'http://10.8.38.232:8300/mult/'





